# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosts',
            name='private_ip',
            field=models.GenericIPAddressField(default='', verbose_name='内网IP'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='ip',
            field=models.GenericIPAddressField(verbose_name='公网IP'),
        ),
    ]
