# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160607_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='archive_dir',
            field=models.CharField(default='', help_text='百度云 archive/2015/wwse', max_length=64, verbose_name='归档目录'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('online', '运维中'), ('offline', '测试中'), ('nothing', '已存档')], max_length=64, verbose_name='项目状态'),
        ),
    ]
