# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160607_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='db_user',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='数据库名称'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='archive_dir',
            field=models.CharField(blank=True, default='', help_text='百度云 archive/2015/wwse', max_length=64, null=True, verbose_name='归档目录'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='db_addr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='数据库地址'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='db_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='数据库名称'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='db_password',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='数据库密码'),
        ),
    ]
