# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160607_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='exp_date',
            field=models.DateField(default='2016-6-6', verbose_name='到期日期'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='db_user',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='数据库用户'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='on_server',
            field=models.ManyToManyField(to='app.Hosts', verbose_name='服务器'),
        ),
    ]
