# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160607_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='ftp',
        ),
        migrations.AddField(
            model_name='projects',
            name='jenkins',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='ssh',
            field=models.TextField(default='', max_length=200, verbose_name='ssh'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='exp_date',
            field=models.DateField(default='2016-6-6', help_text='example: 2016-6-6', verbose_name='到期日期'),
        ),
    ]
